/*
 * BadAsso -> iCalendar: script to paste into the browser console.
 *
 * GENERATED FILE — do not edit by hand.
 * Sources: extension/core.js + console/runner.js, assembled by ./build.sh
 *
 * USAGE
 *   1. Log in to https://bad-asso.fr ("Mon planning" page).
 *   2. Open the console (F12 -> Console).
 *   3. Paste this whole file and hit enter.
 */
/*
 * Shared core: BadAsso API access and iCalendar generation.
 *
 * Single source of truth, shared by:
 *   - the Chrome extension (popup.js, and injected into the page to collect);
 *   - the console script badasso-export.js, generated by ./build.sh;
 *   - the Node tests (test/test-ics.js).
 *
 * Side-effect free: loading it anywhere triggers nothing.
 *
 * User-facing strings stay in French: they are read by club members.
 */
(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.BadAsso = api;
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // "My planning" action: the only endpoint already filtered to one member.
  var MY_PLANNING_ACTION = 729090;
  var TZID = "Europe/Paris";
  var PRODID = "-//badasso-calendar//FR";

  /* ---------------------------------------------------------------- dates */

  // Paris offset ("+02:00") at a given date, daylight saving included.
  function parisOffset(date) {
    var formatter = new Intl.DateTimeFormat("en-US", {
      timeZone: TZID,
      timeZoneName: "longOffset",
    });
    var name = formatter.formatToParts(date).find(function (part) {
      return part.type === "timeZoneName";
    });
    var offset = name ? name.value.replace("GMT", "") : "";
    return offset || "+00:00";
  }

  function toIsoParam(date) {
    var day = new Intl.DateTimeFormat("en-CA", {
      timeZone: TZID,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    }).format(date);
    return day + "T00:00:00" + parisOffset(date);
  }

  // "2026-09-14T12:00" -> "20260914T120000" (local time, carried by TZID)
  function toIcsDate(local) {
    var match = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})(?::(\d{2}))?$/.exec(
      String(local).trim()
    );
    if (!match) return null;
    return match[1] + match[2] + match[3] + "T" + match[4] + match[5] + (match[6] || "00");
  }

  function toUtcStamp(date) {
    return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
  }

  /* ------------------------------------------------------------------ ics */

  function escapeText(value) {
    return String(value == null ? "" : value)
      .replace(/\\/g, "\\\\")
      .replace(/;/g, "\\;")
      .replace(/,/g, "\\,")
      .replace(/\r?\n/g, "\\n");
  }

  // RFC 5545: lines of at most 75 octets, folded with a leading space. The
  // split works on UTF-8 octets rather than characters, otherwise an accented
  // character at the end of a line gets cut in half.
  function foldLine(line) {
    var octets = new TextEncoder().encode(line);
    if (octets.length <= 75) return line;

    var decoder = new TextDecoder();
    var chunks = [];
    var start = 0;
    var limit = 75;
    while (start < octets.length) {
      var end = Math.min(start + limit, octets.length);
      while (end > start && end < octets.length && (octets[end] & 0xc0) === 0x80) {
        end--;
      }
      chunks.push(decoder.decode(octets.subarray(start, end)));
      start = end;
      limit = 74; // following lines lose one octet to the leading space
    }
    return chunks.join("\r\n ");
  }

  /* ---------------------------------------------------------------- color */

  // Subset of the CSS3 named colors, spread across the spectrum.
  var CSS_COLORS = {
    black: [0, 0, 0], dimgray: [105, 105, 105], gray: [128, 128, 128],
    darkgray: [169, 169, 169], silver: [192, 192, 192], lightgray: [211, 211, 211],
    gainsboro: [220, 220, 220], whitesmoke: [245, 245, 245], white: [255, 255, 255],
    maroon: [128, 0, 0], darkred: [139, 0, 0], brown: [165, 42, 42],
    firebrick: [178, 34, 34], red: [255, 0, 0], tomato: [255, 99, 71],
    coral: [255, 127, 80], salmon: [250, 128, 114], lightsalmon: [255, 160, 122],
    orangered: [255, 69, 0], darkorange: [255, 140, 0], orange: [255, 165, 0],
    goldenrod: [218, 165, 32], gold: [255, 215, 0], khaki: [240, 230, 140],
    yellow: [255, 255, 0], olive: [128, 128, 0], yellowgreen: [154, 205, 50],
    darkolivegreen: [85, 107, 47], greenyellow: [173, 255, 47], lawngreen: [124, 252, 0],
    darkgreen: [0, 100, 0], green: [0, 128, 0], forestgreen: [34, 139, 34],
    limegreen: [50, 205, 50], lime: [0, 255, 0], darkseagreen: [143, 188, 143],
    lightgreen: [144, 238, 144], mediumseagreen: [60, 179, 113], seagreen: [46, 139, 87],
    teal: [0, 128, 128], darkcyan: [0, 139, 139], cyan: [0, 255, 255],
    turquoise: [64, 224, 208], cadetblue: [95, 158, 160], lightblue: [173, 216, 230],
    skyblue: [135, 206, 235], steelblue: [70, 130, 180], dodgerblue: [30, 144, 255],
    royalblue: [65, 105, 225], blue: [0, 0, 255], mediumblue: [0, 0, 205],
    navy: [0, 0, 128], midnightblue: [25, 25, 112], slateblue: [106, 90, 205],
    mediumpurple: [147, 112, 219], blueviolet: [138, 43, 226], darkviolet: [148, 0, 211],
    purple: [128, 0, 128], orchid: [218, 112, 214], violet: [238, 130, 238],
    plum: [221, 160, 221], thistle: [216, 191, 216], magenta: [255, 0, 255],
    mediumvioletred: [199, 21, 133], deeppink: [255, 20, 147], hotpink: [255, 105, 180],
    palevioletred: [219, 112, 147], pink: [255, 192, 203], lightpink: [255, 182, 193],
    tan: [210, 180, 140], peru: [205, 133, 63], sienna: [160, 82, 45],
    wheat: [245, 222, 179], beige: [245, 245, 220], lavender: [230, 230, 250],
  };

  // RFC 7986: COLOR expects a CSS3 name, not a hex value. So each venue color
  // is mapped to the closest name by euclidean distance in RGB.
  function nearestCssColorName(hex) {
    var match = /^#?([0-9a-f]{6})$/i.exec(String(hex || "").trim());
    if (!match) return null;
    var packed = parseInt(match[1], 16);
    var red = (packed >> 16) & 255;
    var green = (packed >> 8) & 255;
    var blue = packed & 255;

    var best = null;
    var bestDistance = Infinity;
    Object.keys(CSS_COLORS).forEach(function (name) {
      var rgb = CSS_COLORS[name];
      var distance =
        (rgb[0] - red) * (rgb[0] - red) +
        (rgb[1] - green) * (rgb[1] - green) +
        (rgb[2] - blue) * (rgb[2] - blue);
      if (distance < bestDistance) {
        bestDistance = distance;
        best = name;
      }
    });
    return best;
  }

  function buildIcs(slots, options) {
    var opts = options || {};
    var now = opts.generatedAt || new Date();
    var reminderMinutes = opts.reminderMinutes || 0;

    var lines = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:" + PRODID,
      "CALSCALE:GREGORIAN",
      "METHOD:PUBLISH",
      "X-WR-CALNAME:Badminton",
      "X-WR-TIMEZONE:" + TZID,
      // Without VTIMEZONE, some clients interpret TZID their own way.
      "BEGIN:VTIMEZONE",
      "TZID:" + TZID,
      "BEGIN:DAYLIGHT",
      "TZOFFSETFROM:+0100",
      "TZOFFSETTO:+0200",
      "TZNAME:CEST",
      "DTSTART:19700329T020000",
      "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU",
      "END:DAYLIGHT",
      "BEGIN:STANDARD",
      "TZOFFSETFROM:+0200",
      "TZOFFSETTO:+0100",
      "TZNAME:CET",
      "DTSTART:19701025T030000",
      "RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU",
      "END:STANDARD",
      "END:VTIMEZONE",
    ];

    var skipped = [];

    slots.forEach(function (slot) {
      var start = toIcsDate(slot.start);
      var end = toIcsDate(slot.end);
      if (!start || !end) {
        skipped.push(slot);
        return;
      }

      var details = [];
      if (slot.group_name) details.push("Groupe : " + slot.group_name);
      if (slot.cmt) details.push(slot.cmt);
      details.push("Créneau BadAsso n°" + slot.id);

      lines.push(
        "BEGIN:VEVENT",
        // Stable UID: re-importing the file updates the existing event
        // instead of creating a duplicate.
        "UID:badasso-" + slot.id + "@bad-asso.fr",
        "DTSTAMP:" + toUtcStamp(now),
        "DTSTART;TZID=" + TZID + ":" + start,
        "DTEND;TZID=" + TZID + ":" + end,
        foldLine("SUMMARY:" + escapeText(slot.name || "Badminton")),
        foldLine("LOCATION:" + escapeText(slot.loc_name || "")),
        foldLine("DESCRIPTION:" + escapeText(details.join("\n"))),
        "STATUS:CONFIRMED",
        "TRANSP:OPAQUE"
      );

      var color = nearestCssColorName(slot.loc_color || slot.backgroundColor || slot.color);
      if (color) lines.push("COLOR:" + color);

      if (reminderMinutes > 0) {
        lines.push(
          "BEGIN:VALARM",
          "ACTION:DISPLAY",
          foldLine("DESCRIPTION:" + escapeText(slot.name || "Badminton")),
          "TRIGGER:-PT" + reminderMinutes + "M",
          "END:VALARM"
        );
      }

      lines.push("END:VEVENT");
    });

    lines.push("END:VCALENDAR");
    return { ics: lines.join("\r\n") + "\r\n", skipped: skipped };
  }

  function fileName(date) {
    var day = new Intl.DateTimeFormat("en-CA", {
      timeZone: TZID,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    }).format(date || new Date());
    return "badasso-planning-" + day + ".ics";
  }

  /* --------------------------------------------------------------- fetching */

  function planningUrl(memberId, from, to) {
    return (
      "/index.php?ic_ajax=1&ic_a=" +
      MY_PLANNING_ACTION +
      "&adh_id=" +
      encodeURIComponent(memberId) +
      "&start=" +
      encodeURIComponent(toIsoParam(from)) +
      "&end=" +
      encodeURIComponent(toIsoParam(to))
    );
  }

  // The member id shows up in the page under several forms depending on the
  // screen: a hidden form field, a data-* attribute, or a URL parameter in the
  // calendar bootstrap script.
  function findMemberId() {
    var field = document.querySelector(
      'input[name="adh_id"], input#adh_id, [data-adh_id]'
    );
    if (field) {
      var value = field.value || field.getAttribute("data-adh_id");
      if (value && /^\d+$/.test(String(value).trim())) return String(value).trim();
    }
    var match = /adh_id["'=:\s]+(\d{2,})/.exec(document.documentElement.innerHTML);
    return match ? match[1] : null;
  }

  async function fetchSlots(memberId, from, to) {
    var response = await fetch(planningUrl(memberId, from, to), {
      credentials: "include",
      headers: { "X-Requested-With": "XMLHttpRequest" },
    });
    var body = (await response.text()).trim();

    if (!response.ok) {
      throw new Error("Le serveur a répondu HTTP " + response.status + ".");
    }

    // The content-type is not to be trusted: BadAsso serves its JSON as
    // text/html. Only the response body tells them apart.
    var data;
    try {
      data = JSON.parse(body);
    } catch (err) {
      if (/login|n'avez pas accès/i.test(body)) {
        throw new Error(
          "Le serveur a renvoyé la page de login : ta session a expiré. " +
            "Reconnecte-toi sur bad-asso.fr, puis réessaie."
        );
      }
      throw new Error(
        "Réponse illisible (ni JSON, ni page de login) : " + body.slice(0, 200)
      );
    }

    if (!Array.isArray(data)) throw new Error("JSON inattendu : un tableau était attendu.");
    return data;
  }

  /*
   * Collection entry point, executed in the page context.
   *
   * The result must be serializable: the extension reads it back through
   * chrome.scripting, which conveys neither exceptions nor rich objects. Hence
   * an { ok } object rather than a thrown error.
   */
  async function collect(daysBefore, daysAfter) {
    try {
      var memberId = findMemberId();
      if (!memberId) {
        return {
          ok: false,
          error:
            "Identifiant adhérent introuvable. Ouvre la page « Mon planning » sur bad-asso.fr, puis réessaie.",
        };
      }
      var day = 86400000;
      var slots = await fetchSlots(
        memberId,
        new Date(Date.now() - daysBefore * day),
        new Date(Date.now() + daysAfter * day)
      );
      return { ok: true, memberId: memberId, slots: slots };
    } catch (err) {
      return { ok: false, error: err && err.message ? err.message : String(err) };
    }
  }

  return {
    MY_PLANNING_ACTION: MY_PLANNING_ACTION,
    TZID: TZID,
    buildIcs: buildIcs,
    collect: collect,
    escapeText: escapeText,
    fetchSlots: fetchSlots,
    fileName: fileName,
    findMemberId: findMemberId,
    foldLine: foldLine,
    nearestCssColorName: nearestCssColorName,
    planningUrl: planningUrl,
    toIcsDate: toIcsDate,
  };
});

/*
 * Console script runner. Concatenated after extension/core.js by ./build.sh
 * to produce badasso-export.js, the file to paste into the console.
 *
 * User-facing strings stay in French: they are read by club members.
 */
(async function () {
  "use strict";

  var DAYS_BEFORE = 30;
  var DAYS_AFTER = 365; // wide: trainings are scheduled for the whole season

  if (!/(^|\.)bad-asso\.fr$/.test(location.hostname)) {
    console.error(
      "[BadAsso] À exécuter depuis un onglet ouvert sur https://bad-asso.fr (connecté)."
    );
    return;
  }

  var result = await BadAsso.collect(DAYS_BEFORE, DAYS_AFTER);
  if (!result.ok) {
    console.error("[BadAsso] " + result.error);
    return;
  }

  console.log("[BadAsso] Identifiant adhérent :", result.memberId);

  if (!result.slots.length) {
    console.warn("[BadAsso] Aucun créneau réservé sur la période. Rien à exporter.");
    return;
  }

  var output = BadAsso.buildIcs(result.slots);
  if (output.skipped.length) {
    console.warn(
      "[BadAsso] " + output.skipped.length + " créneau(x) ignoré(s), dates illisibles :",
      output.skipped
    );
  }

  console.log(
    "[BadAsso] " + (result.slots.length - output.skipped.length) + " créneau(x) exporté(s) :"
  );
  console.table(
    result.slots.map(function (slot) {
      return { début: slot.start, fin: slot.end, créneau: slot.name, lieu: slot.loc_name };
    })
  );

  var name = BadAsso.fileName();
  var blob = new Blob([output.ics], { type: "text/calendar;charset=utf-8" });
  var url = URL.createObjectURL(blob);
  var link = document.createElement("a");
  link.href = url;
  link.download = name;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(function () {
    URL.revokeObjectURL(url);
  }, 1000);

  console.log("[BadAsso] Fichier " + name + " généré.");
})();
